### ISSUE TITLE
Normalize ISO 2533 test values in YAML files (exponent values)

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/atmospheric#11]
The test values currently are not harmonized because the exponents are stored as text instead of values.

e.g.
```yml
rows-h:
  - geometrical-altitude: -2000
    pressure-scale-height: 8809.6
    specific-weight: 1.4505 +1
    air-number-density: 3.0735 +25
    mean-speed: 469.19
    frequency: 8.5356 +9
    mean-free-path: 5.4968 -8

  - geometrical-altitude: -1950
    pressure-scale-height: 8800.2
    specific-weight: 1.4438
    air-number-density: 3.0594
    mean-speed: 468.93
    frequency: 8.4919
    mean-free-path: 5.5221
```

Notice that the second set of values, `specific-weight`, `air-number-density` etc do not have the exponent. We need to back fill the exponents if they don't exist.

In the PDF images, the first occurrence of the value provides the exponent and the exponent is omitted in all values in the same column unless they differ.

This task is to normalize these values to proper values so we can do testing.
